# Einführung in Torch

## Aufgabe 1: Eingabe und Arbeit mit Vektoren in pytorch

Erarbeiten Sie sich die grundlegenden Funktionen zur Bibliothek torch mit Hilfe eines frei gewählten Tutorials (z.B. https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html ) und lösen Sie die folgenden Aufgaben. 

Hinweis: Vergessen Sie nicht, die vorgegebenen Befehle auszuführen.

Pytorch-Installation https://pytorch.org/get-started/locally/

In [2]:
import torch

a) Legen Sie einen 3-dimensionalen Vektor a an, der drei beliebige von Ihnen gewählte Werte enthält und multiplizieren Sie ihn mit einem beliebigen Skalar α ∈ R \ 0. Legen Sie das Ergebnis in einem weiteren Vektor b ab.

In [9]:
a = torch.tensor([1., 2., 3.])
alpha = 5.
b = a * alpha

print(a)
print(b)

tensor([1., 2., 3.])
tensor([ 5., 10., 15.])


b) Berechnen Sie das elementweise Produkt der Vektoren a und b und legen Sie das Ergebnis in einem Vektor c ab.

In [10]:
c = a * b
print(c)

tensor([ 5., 20., 45.])


c) Berechnen Sie das Standardskalarprodukt `<a,b>` und speichern Sie das Ergebnis in einem Skalar `s`.

In [11]:
s = c.sum()
print(s)

tensor(70.)


d) Von der folgenden zufällig initialisierten 5x5 Matrix sollen folgende Teile ausgegeben werden (hier Indizes 1-basiert):
 - den Eintrag in der 2-ten Zeile und 4-ten Spalte
 - eine Matrix, die den Eintrag in der 2-ten Zeile und 4-ten Spalte enthält
 - die dritte Spalte
 - die letzte Zeile
 - die Spalten 3 und 4 
 - die Spalten 2,4,5

In [29]:
matrix = torch.rand(5,5)
print(0, matrix)
element_2_4 = matrix[1, 3]
print(1, element_2_4)

matrix_24 = matrix.clone()
matrix_24[0, 0:3] = 0
matrix_24[2:5, 0:3] = 0
matrix_24[0,4] = 0
matrix_24[2:5, 4] = 0
print(matrix_24)
spalt_3 = matrix[:,2]
print(3,spalt_3)
zeile_l = matrix[-1, :]
print(4, zeile_l)
spalt_3_4 = matrix[:, 2:4]
print(5, spalt_3_4)
spalt_245 = matrix[:, [1,3,4]]
print(5, spalt_245)

0 tensor([[0.2210, 0.1539, 0.8237, 0.9665, 0.9343],
        [0.5629, 0.5262, 0.7180, 0.9773, 0.7673],
        [0.9429, 0.8089, 0.4333, 0.3204, 0.4460],
        [0.2476, 0.6391, 0.7850, 0.2627, 0.0823],
        [0.6053, 0.7496, 0.6927, 0.5268, 0.0670]])
1 tensor(0.9773)
tensor([[0.0000, 0.0000, 0.0000, 0.9665, 0.0000],
        [0.5629, 0.5262, 0.7180, 0.9773, 0.7673],
        [0.0000, 0.0000, 0.0000, 0.3204, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.2627, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5268, 0.0000]])
3 tensor([0.8237, 0.7180, 0.4333, 0.7850, 0.6927])
4 tensor([0.6053, 0.7496, 0.6927, 0.5268, 0.0670])
5 tensor([[0.8237, 0.9665],
        [0.7180, 0.9773],
        [0.4333, 0.3204],
        [0.7850, 0.2627],
        [0.6927, 0.5268]])
5 tensor([[0.1539, 0.9665, 0.9343],
        [0.5262, 0.9773, 0.7673],
        [0.8089, 0.3204, 0.4460],
        [0.6391, 0.2627, 0.0823],
        [0.7496, 0.5268, 0.0670]])


e) Berechnen Sie die Spalten-, sowie die Zeilensummen der Matrix `mat`.

In [33]:
sum_column = torch.sum(matrix, dim = 1)
print(sum_column)
sum_row = torch.sum(matrix, dim = 0)
print(sum_row)

tensor([3.0993, 3.5518, 2.9515, 2.0168, 2.6413])
tensor([2.5797, 2.8778, 3.4528, 3.0537, 2.2968])


f) Erzeugen Sie den Vektor [0, ..., 9] mithilfe von `torch.arange` und `torch.linspace`.

In [38]:
v = torch.arange(0,10,1.0)
print(v)
v1 = torch.linspace(0, 9, 10)
print(v1)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


# Single Layer Perceptron Basic für XOR

In [8]:
import torch
import matplotlib.pyplot as plt
import numpy as np

## Aufgabe 1

Implementieren Sie die Klasse für ein einlagiges Perzeptron (single layer perceptron, SLP). 
Nutzen Sie das Grundgerüst.

In [85]:
class SLP():
    """
    Single Layer Perceptron
    """
    
    weights = torch.tensor([1., 1.])
    b = 0.
    
    def __init__(self):
        """ Initialisierung der Gewichte (torch.tensor) und des Schwellwertes (skalar). """
        pass

    def net_input_function(self , inp):
        """ Netzeingabefunktion: Gewichtete Summe der Eingaben (torch.tensors). """
        result = torch.sum(inp * self.weights).item()
        print(result)
        return result

    def activation_function(self, val):
        """ Aktivierungsfunktion: Schwellwertfunktion. """
        if  val > self.b:
            return 1
        else:
            return 0
    
    def set_weights(self, weights):
        """ Setzen der Gewichte des SLP. """
        self.weights = weights
    
    def set_bias(self, bias):
        """Setzen des Schwellenwertes des SLP. """
        self.b = bias

    def get_output(self, inp):
        """ Berechnen der Ausgabe des Neurons: Für einen Input wird zuerst die 
        Netzeingabefunktion und darauf die Aktivierungsfunktion angewendet. Das 
        Ergebnis wird ausgegeben. """
        return self.activation_function(self.net_input_function(inp))


In [86]:
slp = SLP()
slp.set_weights(torch.tensor([1, 10]))
slp.set_bias(5)

slp.net_input_function(torch.tensor([2, 0.4]))


6.0


6.0

In [87]:
# soll 1 ausgeben
print(slp.get_output(torch.tensor([2, 0.4])), '== 1?')

# soll 0 ausgeben
print(slp.get_output(torch.tensor([0, 0.4])), '== 0?')

6.0
1 == 1?
4.0
0 == 0?


## Aufgabe 2
Erstellen Sie 3 Perzeptren, welche die Funktionen **OR**, **AND** und **XOR** abbilden. Setzen Sie dazu die passende Gewichte $w$ und Schwellwerte $\theta$.

In [2]:
def test_slp(slp, instances, targets):
    for instance, target in zip(instances, targets):
        label = slp.get_output(instance)
        print(instance, '|', label, '|', target, '| equal =', label==target)

    xs = np.arange(-1,3,0.1)
    X1,X2 = np.meshgrid(xs,xs)
    Theta = np.vstack([X1.ravel(), X2.ravel()]).T
    Z = np.asarray([slp.get_output(torch.tensor(x)) for x in Theta]).reshape(len(xs),len(xs))
    plt.figure(figsize=(3,3))
    plt.text(0,.2, "   $slp(x)=0$")
    plt.text(.8,.74, "   $slp(x)=1$")
    plt.contour(xs, xs, Z, colors='k', levels=0, edgecolor='k', zorder=4)
    for i in range(0,len(instances)):
        plt.scatter(instances[i][0], instances[i][1], marker='o', edgecolor='k', label=f"({instances[i].numpy()},{targets[i]})")
    #plt.scatter(*instances.T, marker='o', edgecolor='k', c='m')

    plt.xticks([0,1])
    plt.yticks([0,1])
    plt.xlim([-0.1,1.1])
    plt.ylim([-0.1,1.1])
    plt.xlabel("$x_1$")
    plt.ylabel("$x_2$")
    plt.legend()
    plt.tight_layout()
    plt.show()

In [ ]:
# OR: 
slp_or = SLP()
### TODO ###
slp_or.set_weights(torch.tensor([0,0]))
slp_or.set_bias(0.0)

In [ ]:
test_slp(slp_or, torch.tensor([[0,0], [0,1], [1,0], [1,1]]), torch.tensor([0,1,1,1]))

In [ ]:
# AND: 
slp_and = SLP()
### TODO ###
slp_and.set_weights(torch.tensor([0,0]))
slp_and.set_bias(0.0)

In [ ]:
test_slp(slp_and, torch.tensor([[0,0], [0,1], [1,0], [1,1]]), torch.tensor([0,0,0,1]))

In [ ]:
# XOR: 
slp_xor = SLP()
### TODO ###
slp_xor.set_weights(torch.tensor([0,0]))
slp_xor.set_bias(0.0)

In [ ]:
test_slp(slp_xor, torch.tensor([[0,0], [0,1], [1,0], [1,1]]), torch.tensor([0,1,1,0]))