# Single Layer Perceptron mit Trainingsmethode für XOR

In [1]:
import torch

# Aufgabe 1 (Fit Methode)

Implementieren Sie eine Trainingsmethode für Ihr erstelltes SLP. Es soll die Funktion **OR** und **AND** lernen können.

In [2]:
class SLP():
    """
    Single Layer Perceptron
    """

    def __init__(self):
        """ Initialisierung der Gewichte (torch.tensor) und des Schwellwertes (skalar). """
        self.weights = torch.zeros(2)
        self.threshold = 0

    def net_input_function(self, inp):
        """ Netzeingabefunktion: Gewichtete Summe der Eingaben (torch.tensors). """
        return torch.sum(inp * self.weights)

    def activation_function(self, val):
        """ Aktivierungsfunktion: Schwellwertfunktion. """
        return torch.tensor(int(val > self.threshold),dtype=torch.float32)

    def set_weights(self, weights):
        """ Setzen der Gewichte des SLP. """
        self.weights = weights

    def set_threshold(self, threshold):
        """Setzen des Schwellenwertes des SLP. """
        self.threshold = threshold

    def get_output(self, inp):
        """ Berechnen der Ausgabe des Neurons: Für einen Input wird zuerst die 
        Netzeingabefunktion und darauf die Aktivierungsfunktion angewendet. Das 
        Ergebnis wird ausgegeben. """
        return self.activation_function(self.net_input_function(inp))

    def fit(self, X, y, epochs, learning_rate=.5):
        """Training des SLP."""
        for epoche in range(epochs):
            for x_i, y_i in zip(X,y):
                y_pred = self.get_output(x_i)
                error = y_i - y_pred
                delta = learning_rate * error * x_i
                self.weights += delta
                self.threshold -= learning_rate * error
        

In [3]:
def test_slp(slp, instances, targets):
    for instance, target in zip(instances, targets):
        label = torch.round(slp.get_output(instance))
        print(instance, '|', label, '|', target, '| equal =', label==target)

In [5]:
# Trainingsdaten AND
X, y = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]],dtype=torch.float32), torch.tensor([0, 0, 0, 1],dtype=torch.float32)
epochs = 10
slp_and = SLP()
slp_and.fit(X, y, epochs)

In [6]:
test_slp(slp_and, X, y)

tensor([0., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([0., 1.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([1., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([1., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)


In [7]:
# Trainingsdaten OR
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]],dtype=torch.float32)
y = torch.tensor([0, 1, 1, 1],dtype=torch.float32)
epochs = 10
slp_or = SLP()
slp_or.fit(X, y, epochs)

In [8]:
test_slp(slp_or, X, y)

tensor([0., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([0., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)
tensor([1., 0.]) | tensor(1.) | tensor(1.) | equal = tensor(True)
tensor([1., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)


# Aufgabe 2 (Sigmoid)
Implementieren Sie nun das Training und benutzen Sie eine sigmoide Funktion. Berechnen Sie dazu die Ableitung der Fehlerfunktion um die Gewichts- und Schwellwertänderung zu erhalten.

\begin{align}
\mathcal{E}(k) &= \frac{1}{2}(y - t)^2\\
y &= \frac{1}{ 1+e^{-\left(\sum{wx} + \theta\right)}}\\
\end{align}

In [33]:
class SLP_sigmoid():
    """
    Single Layer Perceptron
    """

    def __init__(self):
        """ Initialisierung der Gewichte (torch.tensor) und des Schwellwertes (skalar). """
        self.weights = torch.zeros(2)
        self.threshold = 0

    def net_input_function(self, inp):
        """ Netzeingabefunktion: Gewichtete Summe der Eingaben (torch.tensors). """
        return torch.sum(inp * self.weights)

    def activation_function(self, val):
        """ Aktivierungsfunktion: Schwellwertfunktion. """
        return 1 / (1 + torch.exp(-(val + self.threshold)))

    def set_weights(self, weights):
        """ Setzen der Gewichte des SLP. """
        self.weights = weights

    def set_threshold(self, threshold):
        """Setzen des Schwellenwertes des SLP. """
        self.threshold = threshold

    def get_output(self, inp):
        """ Berechnen der Ausgabe des Neurons: Für einen Input wird zuerst die 
        Netzeingabefunktion und darauf die Aktivierungsfunktion angewendet. Das 
        Ergebnis wird ausgegeben. """
        return self.activation_function(self.net_input_function(inp))

    def fit(self, X, y, epochs, learning_rate=.5):
        """Training des SLP."""
        for epoche in range(epochs):
            for x_i, y_i in zip(X,y):
                y_pred = self.get_output(x_i)
                error = 1/2 * (y_pred - y_i)**2
                
                exp_term = torch.exp(-(self.net_input_function(x_i) + self.threshold))
                term_1 = 1/(1+exp_term) - y_i
                term_2 = -(1+exp_term)**-2
                
                deviation_w = term_1 * term_2 * (-x_i * exp_term)
                deviation_b = term_1 * term_2 * -1 * exp_term
                
                delta_w = deviation_w * learning_rate
                delta_b = deviation_b * learning_rate
                
                self.weights -= delta_w
                self.threshold -= delta_b

In [34]:
# Trainingsdaten AND
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]],dtype=torch.float32)
y = torch.tensor([0, 0, 0, 1],dtype=torch.float32)
epochs = 100
slp_and_sig = SLP_sigmoid()
slp_and_sig.fit(X, y, epochs)

In [35]:
test_slp(slp_and_sig, X, y)

tensor([0., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([0., 1.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([1., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([1., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)


In [38]:
# Trainingsdaten OR
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]],dtype=torch.float32)
y = torch.tensor([0, 1, 1, 1],dtype=torch.float32)
epochs = 100
slp_or_sig = SLP_sigmoid()
slp_or_sig.fit(X, y, epochs)

In [39]:
test_slp(slp_or_sig, X, y)

tensor([0., 0.]) | tensor(0.) | tensor(0.) | equal = tensor(True)
tensor([0., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)
tensor([1., 0.]) | tensor(1.) | tensor(1.) | equal = tensor(True)
tensor([1., 1.]) | tensor(1.) | tensor(1.) | equal = tensor(True)
